
import random
import sys
from typing import List
import os


def generar_array(size: int, element_size: int = 1000) -> List[int]:
    array = random.sample(range(1, element_size), size)

    os.makedirs("test_cases/autogenerated", exist_ok=True)

    with open(f"test_cases/autogenerated/{size}.txt", 'w') as file:
        file.write(";".join(str(i) for i in array))
    return array

if __name__ == "__main__":
  if len(sys.argv) != 3:
        print("Argumentos incorrectos.\nUso: python3 generador.py <tamaño max arreglo> <valor maximo de moneda>")
  max_len = int(sys.argv[1])
  max_coin = int(sys.argv[2])

  if max_coin < max_len:
    print("El valor maximo de las monedas debe ser mayor o igual al tamaño maximo del arreglo a generar")

  for i in range(1, int(max_len)+1):
    generar_array(i, max_coin)